# Required to run your project under the correct environment.
language: php

# Versions of PHP you want your project run with.
php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3

notifications:
  email: false

# Commands to be run before your environment runs.
before_script:
  - composer update --no-interaction --no-suggest
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

# Commands you want to run that will verify your build.
script: vendor/bin/phpunit --stderr

# Commands to be run after your environment runs.
after_script:
  - ./cc-test-reporter after-build --coverage-input-type clover --id d4952effc6e0e3b3c2aabb5a352bbc97aa1d23f3f7560214f8c145f43ef951b0 --exit-code $TRAVIS_TEST_RESULT
