name: Laravel 5.5

on: [push, pull_request]

jobs:
  phpunit:
    runs-on: ubuntu-18.04

    strategy:
      fail-fast: false

      matrix:
        php-versions: ['7.0', '7.1', '7.2', '7.3', '7.4']

    steps:
      - uses: actions/checkout@v1

      - name: Setup PHP, Composer and Extensions
        uses: shivammathur/setup-php@master
        with:
          php-version: ${{ matrix.php-versions }}
          extension-csv: dom, mbstring, xdebug

      - name: Install testbench and phpunit
        run: composer require "orchestra/testbench:3.5.*" "phpunit/phpunit:6.5.*" --dev --no-interaction --no-suggest --no-update

      - name: Install dependencies
        run: composer update --optimize-autoloader --prefer-dist --no-interaction --no-progress --no-suggest

      - name: Run tests
        run: php vendor/bin/phpunit
